src/lib/Header/Header.stories.js
src/lib/Header/style/index.js
src/lib/Logo/Logo.js
src/lib/Logo/Logo.stories.js
src/lib/Logo/style/base.js
src/lib/Logo/style/index.js
src/theme/theme.base.js

- Ajout de props `text` et `textSize` pour ajouter un badge à un Logo
- Edit Header pour retirer le CSS custom : désormais, la taille du Logo doit être définie par une props sur le Logo dans le Header
**Pour tester :** 
Aller sur le composant Logo et renseigner un texte (par exemple : FAQ). Modifier les tailles du blockWidth et du textSize pour vérifier que tout va bien.
Note : un logo en blockWidth sm ira bien avec un textSize md, ces deux valeurs ne sont pas identiques.
Penser aussi à tester le Header qui contient un logo.

PGX-4231 : update Logo component

---

src/lib/Corner/Corner.js
src/lib/Corner/Corner.stories.js
src/lib/Corner/__snapshots__/Corner.test.js.snap
src/lib/Corner/style/base.js
src/lib/Corner/style/index.js
src/lib/Main/style/base.js

Ajout d'une props hasCenteredPopin sur le composant Corner pour permettre de centrer la popin par rapport au Corner (utile en particulier sur les versions mobiles).
Fix visuel sur l'ombre visible du Main fermé.

PGF-287: custom corner popin position

---

src/lib/Grid/style/base.js
src/lib/MenuClose/MenuClose.js
src/lib/MenuClose/MenuClose.stories.js

Ajout d'une props isOpen sur le composant MenuClose pour pouvoir tourner la flèche dans le bon sens dans une Card qui le contient (exemple : BO Green card des projets).
Customisation du gap des colonnes dans la Grid.

PGF-251 : add isOpen props on MenuClose component

---

src/lib/Grid/style/base.js

- Ajout d'un `!important` sur les margin-top des enfants d'une grille décalée (pour contrer un fix plus récent sur les marges des enfants d'une grille).

PGF-552: fix margins for shifted grids

---

src/lib/Header/Header.js
src/lib/Header/Header.stories.js

- Ajout d'une props `hasTopStyle` sur le Header (à `true` par défaut) pour permettre de retirer la transparence des menus lorsque l'on est en scroll 0 : cela permet de pouvoir se passer d'un bandeau coloré en haut de page.
(snapshots inchangés, les tests passent toujours bien ✔️ )

PGF-551: add hasTopStyle props on Header to remove transparency option

---

src/lib/Table/Table.js
src/lib/Table/Table.stories.js
src/lib/Table/__snapshots__/Table.test.js.snap
src/lib/Table/style/base.js
src/lib/Table/style/index.js

Ajout d'une option `hasOverflowEmphasis` pour les composants **Table** : elle permet de dégrader l'overflow des tableaux sur petit écran et plus simplement de tronquer de manière nette, afin de mieux indiquer que le tableau s'étend vers la droite.

PGF-587: add overflowEmphasis option for Table

---

src/lib/Checkbox/Checkbox.js
src/lib/DaTable/DaTable.js
src/lib/DaTable/DaTable.stories.js
src/lib/DaTable/style/index.js
src/lib/DaTableBody/DaTableBody.js
src/lib/DaTableCell/DaTableCell.js
src/lib/DaTableCell/DaTableCell.stories.js
src/lib/DaTableCell/style/base.js
src/lib/DaTableCell/style/index.js
src/lib/DaTableHead/DaTableHead.js
src/lib/DaTableHead/DaTableHead.stories.js
src/lib/DaTableHeadCell/DaTableHeadCell.js
src/lib/DaTableHeadCell/style/base.js
src/lib/DaTableHeadCell/style/index.js
src/lib/DaTableRow/DaTableRow.js
src/lib/DaTableRow/style/base.js
src/lib/DaTableRow/style/index.js
src/lib/SkeletonItem/style/base.js
src/lib/SkeletonItem/style/constants.js
src/lib/SkeletonItem/style/index.js
src/theme/theme.base.js

- Amélioration des couleurs du reflet animé des **SkeletonItem** (meilleure visibilité sur fond très clair ou très foncé)
- Retrait de la props `resultsLabel` dans le **DaTableHead** (jamais utilisée et inutile)
- Retrait de la props `field` dans le **DaTableCell** (jamais utilisée et inutile)
- Styles du **DaTable** en cours de chargement
- Styles du **DaTable** sans données

PGF-523: improve DaTable

---

src/lib/Dropdown/Dropdown.js

- ajout d'un hook pour fermer le dropdown quand on clique à l'extérieur s'il n'y a pas d'overlay
- dans la story du dropdown, "dropdown with clickable block" : 
- si hasOverlay est true :  au clic à l'extérieur le dropdown se ferme
- si hasOverlay est false : au clic à l'extérieur ça se ferme aussi :)     
@OliviaGometz je ne voulais pas compliquer la story donc je n'ai rien rajouté d'autre mais j'ai fait un test d'intégration dans le BO ClimateKit et ça marche :)

PGF-666: Added hook to detect outside click and close dropdown component

---

src/lib/Histogram/Histogram.js
src/lib/Histogram/Histogram.stories.js
src/lib/Histogram/YAxis/YAxis.js
src/lib/Histogram/YAxis/YAxis.test.js
src/lib/Histogram/YAxis/__snapshots__/YAxis.test.js.snap
src/lib/Histogram/__snapshots__/Histogram.test.js.snap
src/lib/HistogramBar/HistogramBar.js
src/lib/HistogramBar/HistogramBar.stories.js
src/lib/HistogramBar/HistogramBar.test.js
src/lib/HistogramBar/__snapshots__/HistogramBar.test.js.snap
src/shared/tools.js

- suppression de l'arrondi sur le y axis
- ajout d'une méthode dans tools.js pour limiter le nombre de décimales dans les chiffres du y axis
- ajout d'une props "yaxisMaxValueLabel"  pour gérer la MaxValue (qui gère le calcul de l'ensemble des éléments) et la MaxValue "convertie" dans le y axis 
- dans histogramBar , enrichissement de la props " legend" pour éviter les warnings côté BO avec react i18next
- update des tests
- pas d'ajout de la props yaxisMaxValueLabel en stories car pas utile
- tester l'ensemble du comportement de Histogram et HistogramBar  dans storybook avec notamment les knobs en dynamique

PGF-709 : update de l'histogram et histogrambar

---

package.json
src/lib/Char/Char.js
src/lib/Char/Char.stories.js
src/lib/Char/Char.test.js
src/lib/Char/__snapshots__/Char.test.js.snap
src/lib/index.js
src/shared/constants.js
yarn.lock

Création du composant Char, qui permet de faire plein de petits choses sympas sur des chaînes de caractères : 
- Tronquer quand c'est trop long
- Masquer certains caractères pour les données sensibles
Plein de choses sont paramétrables : caractères à afficher au début et à la fin de la chaîne, caractères qui restent "en clair" même s'ils sont dans la zone à masquer (exemple : les espaces dans des IBAN, même si on masque les numéros, on peut avoir envie de garder les espaces sans les remplacer par des astérisques), caractères de remplacement (... pour les chaînes tronquées, * pour les chaînes masquées, et c'est donc paramétrable), etc.
Ce composant renvoie une string, c'est donc utilisable dans n'importe quel parent sans aucun impact sur le style.

PGF-699 : Char component

---

src/lib/DaInput/DaInput.js
src/lib/DaInput/DaInput.stories.js
src/lib/DaInput/__snapshots__/DaInput.test.js.snap
src/lib/DaInput/style/base.js
src/lib/DaInput/style/index.js
src/lib/DaSelect/DaSelect.js
src/lib/DaSelect/DaSelect.stories.js
src/lib/DaSelect/__snapshots__/DaSelect.test.js.snap
src/lib/DaSelect/style/index.js
src/lib/DaTextarea/DaTextarea.js
src/lib/DaTextarea/DaTextarea.stories.js
src/lib/DaTextarea/__snapshots__/DaTextarea.test.js.snap
src/lib/DaTextarea/style/base.js
src/lib/DaTextarea/style/index.js
src/lib/FormControl/FormControl.js
src/lib/FormControl/FormControl.stories.js
src/lib/FormControl/style/base.js

- ajout d'un booléen `hasStaticWidth` au DaSelect, DaInput, DaTextarea pour avoir une width à 100% quand nécessaire
- update du `FormControl` pour passer la props à tous les enfants qui en ont besoin
-  `yarn start` 
- les stories du `FormControl`, `DaInput, `DaSelect`, `DaTextarea`

PGF-773 : Fix sur les DaInput, DaSelect, DaTextarea pour avoir un width à 100%

---

src/lib/DaHelp/DaHelp.js
src/lib/DaHelp/DaHelp.stories.js
src/lib/DaHelp/__snapshots__/DaHelp.test.js.snap
src/lib/DaHelp/style/base.js
src/lib/DaHelp/style/index.js
src/lib/DaInput/DaInput.js
src/lib/DaInput/DaInput.stories.js
src/lib/DaInput/__snapshots__/DaInput.test.js.snap
src/lib/DaInput/style/base.js
src/lib/DaInput/style/constants.js
src/lib/DaInput/style/index.js
src/lib/DaSelect/DaSelect.js
src/lib/DaSelect/DaSelect.stories.js
src/lib/DaSelect/__snapshots__/DaSelect.test.js.snap
src/lib/DaSelect/style/constants.js
src/lib/DaSelect/style/index.js
src/lib/DatePicker/Calendar/Calendar.test.js
src/lib/DatePicker/CalendarNavbar/CalendarNavbar.test.js
src/lib/DatePicker/DatePicker.js
src/lib/DatePicker/DatePicker.stories.js
src/lib/DatePicker/DatePicker.test.js
src/lib/DatePicker/__snapshots__/DatePicker.test.js.snap
src/lib/FormControl/FormControl.stories.js
src/lib/FormControl/__snapshots__/FormControl.test.js.snap
src/lib/FormControl/style/base.js
src/shared/global.js

- Ajout d'icons via uen props `icon` dans les DaInput, DaSelect (et DatePicker via son DaInput). Les tailles et couleurs sont gérées automatiquement par les composants parents, y'a juste à glisser l'icon de son choix et pof ça marche 🎉 
- Fix du padding-right des DaSelect
- Fix de l'opacité des select disabled (merci Chrome t'es le meilleur change rien 🖕 )
- Retrait de l'option "disabled" dans les DaHelp (c'est inutile, si on veut pas aider l'utilisateur on n'affiche pas le bouton, pas la peine de lui flanquer le seum)
- Fix dans les tests de certains composants du DatePicker pour éviter que les snapshots changent à chaque mois (maintenant c'est bon, avant j'avais juste fixé les changements de jour, mais là normalement même les changements d'années devraient plus MAJ les snapshots, c'est …

PGF-246 : ajout de la possibilité de mettre un icon à l'intérieur des DaInput, DaSelect et DatePicker

---

src/lib/Button/__snapshots__/Button.test.js.snap
src/lib/Button/style/base.js
src/lib/Button/style/constants.js
src/lib/Button/style/index.js
src/lib/ButtonGroup/__snapshots__/ButtonGroup.test.js.snap
src/lib/Card/__snapshots__/Card.test.js.snap
src/lib/DaButton/__snapshots__/DaButton.test.js.snap
src/lib/DaButton/style/base.js
src/lib/DaButton/style/constants.js
src/lib/DaButton/style/index.js

-------
Fix sur les composants **Button** et **DaButton** : désormais, lorsqu'ils sont `disabled`, ils n'ont aucun effet au `hover`.
Explication du bug
-------
Le bug provenait de la structure du CSS (avec styled-components, il est vite périlleux de faire du style conditionnel lorsque celui-ci touche à un composant dont le style est visible lorsqu'il est contenu à l'intérieur d'une autre balise HTML). Exemple de CSS sujet à bugs : 
```css
button:hover &,
button:active &,
button:focus &,
a:hover &,
a:active &,
a:focus & {
&::before {
transform: scale(1);
}
}
```
Seul, ce bout de CSS fonctionne bien, mais s'il est contenu dans une variable appelée de manière conditionnelle (exemple : `${props => (props.isDisabled ? disabledStyle : null)};`), il "persiste" même si la …

PGF-732: disabled Button and DaButton without hover style (fix)

---

src/lib/Toggle/__snapshots__/Toggle.test.js.snap
src/lib/Toggle/style/index.js

Le Toggle fonctionne bien avec de petits textes, mais dès que ce sont des mots trop longs ou inégaux, ça se passe moyen.
- Diminution de la taille du texte
- Display flex pour avoir un rendu bien centré
- Utilisation de la font comme élément d'apparition/disparition plutôt qu'un transform, qui reste "visible" dans le container (ce qui donne des Toggle super larges)

PGF-916: fix CSS for text inside Toggle

---

src/lib/Checkbox/Checkbox.js
src/lib/Checkbox/Checkbox.stories.js
src/lib/Checkbox/Checkbox.test.js
src/lib/CheckboxGroup/CheckboxGroup.js
src/lib/DaSelect/DaSelect.js
src/lib/DaSelect/DaSelect.stories.js
src/lib/DaTable/DaTable.test.js
src/lib/DaTable/__snapshots__/DaTable.test.js.snap
src/lib/DaTableBody/DaTableBody.test.js
src/lib/DaTableHead/DaTableHead.test.js
src/lib/DaTableRow/DaTableRow.test.js
src/lib/Radio/Radio.js
src/lib/Radio/Radio.stories.js
src/lib/Radio/Radio.test.js
src/lib/Radio/__snapshots__/Radio.test.js.snap
src/lib/RadioGroup/RadioGroup.js
src/lib/Select/Options.js
src/lib/Select/Select.js

----
- Autoriser tous les types de `value` dans les composants de formulaire (**CheckboxGroup** & **Checkbox**, **RadioGroup** & **Radio**, **Select**, **DaSelect**)(et dans le **Options** contenu dans le composant **Select**).
- Rendre obligatoire le `label` et la `value` dans le composant **Radio** (autant dans la **Checkbox**, on peut avoir des cas où on n'en a pas besoin - exemple : dans un tableau, la **Checkbox** peut servir pour sélectionner des lignes, ce n'est donc pas un usage "formulaire" dans lequel la value est indispensable), autant le **Radio** n'a d'intérêt qu'avec une `value`.
- Retrait des **Checkbox** dans le fichier de test du **DaTable** (déjà testé ailleurs et ici, c'était mal fichu puisque toutes les **Checkbox** avaient le même `id`, c'était pas …

PGF-949: autoriser tous les types de value dans les composants de formulaire et autoriser les objets comme legend

---

src/lib/IconLabel/IconLabel.js
src/lib/IconLabel/IconLabel.stories.js
src/lib/IconLabel/IconLabel.test.js
src/lib/IconLabel/__snapshots__/IconLabel.test.js.snap
src/lib/IconLabel/style/base.js
src/lib/IconLabel/style/index.js
src/lib/Menu/Menu.stories.js
src/lib/MenuGroup/MenuGroup.stories.js
src/lib/MenuList/MenuList.stories.js
src/lib/MenuListItem/MenuListItem.stories.js
src/lib/MenuListItem/MenuListItem.test.js
src/lib/MenuListItem/__snapshots__/MenuListItem.test.js.snap
src/lib/MenuPrimary/MenuPrimary.stories.js
src/lib/MenuPrimary/MenuPrimary.test.js
src/lib/MenuPrimary/__snapshots__/MenuPrimary.test.js.snap

------
- Autoriser le passage de l'icon dans une props `icon` (optionnelle) sur le **IconLabel** : l'ancienne intégration reste valable, mais celle-ci permet de ne pas gérer les couleurs et tailles d'icons.
- Ajout du `colorPallet` `status`
- Refacto des stories et tests de composants embarquant des **IconLabel**
Comment tester
------
- Tester les couleurs sur la storie de l'IconLabel et vérifier qu'il n'y a pas d'erreur en console
- Afficher les stories des composants Menu, MenuList, MenuListItem, MenuPrimary et MenuGroup et vérifier qu'il n'y a pas d'erreur en console et que les IconLabel ont des couleurs cohérentes (genre pas un icon rouge dans un label vert)

PGF-982: improve IconLabel

---

src/lib/DaTextarea/DaTextarea.js
src/lib/GlobalStyle/ResetStyle.js
src/lib/Textarea/Textarea.js

- Prise en compte du `defaultValue` sur les composants **Textarea** et **DaTextarea** : si on définit une `defaultValue`, elle sera bien prise en compte (au même titre que la `value`) et il n'y aura plus d'erreur en console
- Ajout d'un bout de CSS pour couper les mots longs (genre `aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa` merci Maxime ~~de nous emmerder~~ pour son aide) sur l'ensemble des composants 👌

PGF-1005: prise en compte du defaultValue sur Textarea et DaTextarea

---

src/lib/Toggle/Toggle.js
src/lib/Toggle/Toggle.stories.js
src/lib/Toggle/Toggle.test.js
src/lib/Toggle/ToggleLabel.js
src/lib/Toggle/__snapshots__/Toggle.test.js.snap
src/lib/Toggle/style/constants.js
src/lib/Toggle/style/index.js
src/theme/theme.base.js

-------
- On peut désormais choisir la couleur du disabled du Toggle : pour toutes les props de couleur (`colorPallet`, `colorTheme`, `colorWab` et `colorStatus`), on peut passer soit une string (fonctionnement initial), soit un tableau : 
```
colorPallet={
checked: 'status',
notChecked: 'wab
}
```
Si une string est passée, la couleur du disabled sera la même qu'auparavant (ces changements de couleur sont donc totalement rétro-compatibles).
- Ajout d'une props `fieldSize` (`sm`, `md` ou `lg` - `md` par défaut) pour choisir la taille du Toggle. Celui-ci a été un peu réduit dans sa taille par défaut afin de mieux s'intégrer avec d'autres champs.
- La props `legend` a été retirée afin de simplifier le Toggle déjà très complet. Par ailleurs, cela permettra de mieux adapter …

PGF-1010: permettre de customiser les couleurs du Toggle

---

src/colors.stories.mdx
src/lib/CheckboxGroup/CheckboxGroup.js
src/lib/CheckboxGroup/CheckboxGroup.stories.js
src/lib/DaTable/DaTable.stories.js
src/lib/DaTable/__snapshots__/DaTable.test.js.snap
src/lib/DaTableBody/__snapshots__/DaTableBody.test.js.snap
src/lib/DaTableHead/__snapshots__/DaTableHead.test.js.snap
src/lib/DaTableHeadCell/DaTableHeadCell.js
src/lib/DaTableHeadCell/__snapshots__/DaTableHeadCell.test.js.snap
src/lib/DaTableHeadCell/style/index.js
src/lib/DaTableRow/DaTableRow.js
src/lib/DaTableRow/DaTableRow.stories.js
src/lib/DaTableRow/__snapshots__/DaTableRow.test.js.snap
src/lib/DaTableRow/style/base.js
src/lib/DataLegend/DataLegend.js
src/lib/GlobalStyle/ResetStyle.js
src/lib/Modal/__snapshots__/Modal.test.js.snap
src/lib/ModalContent/__snapshots__/ModalContent.test.js.snap
src/lib/ModalContent/style/index.js
src/lib/ModalProvider/__snapshots__/ModalProvider.test.js.snap

------
**ModalContent**
- feat: la hauteur maximale est passée de 80 à 90vh pour mieux utiliser l'espace dont on dispose et limiter les scrollbar évitables
**DataLegend**
- feat: on autorise désormais les `string` sur la props `value` (et plus uniquement les `number`)
**DaSelect**
- fix: ajout d'un reset global sur les select pour passer le line-height en "normal" par défaut, et éviter que les jambages des lettres soient coupées dans les DaSelect. Sans effet sur le composant Select qui intègre son propre line-height.
**DaTable**
- fix: le DaTableHeadCell ne duplique plus les Checkbox qui lui sont passés (et celle qui lui est passé est donc cliquable, plus de bug d'id dupliqué)
- fix: vertical-align top sur le DaTableHeadCell (le bug n'existait pas une fois que le …

PGF-1080: fix multiples sur les DaTable, Modal, DataLegend, CheckboxGroup et DaSelect

---

src/lib/DaTable/DaTable.js
src/lib/DaTable/__snapshots__/DaTable.test.js.snap
src/lib/DaTableBody/__snapshots__/DaTableBody.test.js.snap
src/lib/DaTableRow/DaTableRow.js
src/lib/DaTableRow/__snapshots__/DaTableRow.test.js.snap
src/lib/DaTableRow/style/index.js

- ajout de la détection des classes lors de la construction automatique du DaTable et update des tests
- diminution des transitions sur le datablerow
- lancer storybook 
- vérifier que le layout desktop / mobile n'a pas bougé sur DaTable, DaTableBody,
-  puis dans le fichier DaTable.stories :
1) rajouter ce composant :
```
const MemoizedRow = memo(({ className, children, isActive }) => {
return (
<DaTableRow isActive={isActive} className={className}>
{children}
</DaTableRow>
);
});
```
et remplacer le DaTableRow (lignes 226 - 257) 
par ```
<MemoizedRow
key={index}
isActive={isActive}
className="DaTableRow"
>
```
=> vérifier que le layout n'a pas sauté (desktop et mobile)
- cleaner le fichier puis 
rajouter ce composant :
```
const MemoizedBody = memo(({ className, children }) => {
return …
```

PGF-1089 : Fix datable

---

src/lib/DatePicker/Calendar/__snapshots__/Calendar.test.js.snap
src/lib/DatePicker/CalendarGrid/__snapshots__/CalendarGrid.test.js.snap
src/lib/DatePicker/CalendarNavbar/__snapshots__/CalendarNavbar.test.js.snap
src/lib/DatePicker/DatePicker.js
src/lib/DatePicker/DatePicker.stories.js
src/lib/Text/style/base.js
src/lib/Title/style/base.js

- fix sur le datepicker pour permettre l'update de la value interne avec une valeur vide (indépendamment des contraintes dates min/max/resetdate) 
- fix sur le composant text où l'underline était sans couleur et fix sur le padding nécessaire à son positionnement sous le bloc de texte (vue avec Olivia, il y a une disparition du padding notamment en mobile, due aux `${responsiveSpaces('padding')};` appliqués sur le composant `Text`. pour faire simple et limiter les risques de régressions on ne touche pas cette fonction , on n'ajoute pas d'exception dessus, on rajoute exceptionnellement un `!important` dans le bloc de style dédié à l'`underline` pour garantir le padding.)
- `yarn start`
- tester la story du composant Text, cocher hasUnderline => cette fois il est visible, tester le …

PGF-1093: fix datepicker et text
