PayGreen/paygreen-ui

src/lib/AutonomousInput/__snapshots__/AutonomousInput.test.js.snap, src/lib/Banner/__snapshots__/Banner.test.js.snap, src/lib/Banner/style/index.js, src/lib/Divider/Divider.js, src/lib/Divider/Divider.stories.js, src/lib/Divider/Divider.test.js, src/lib/Divider/__snapshots__/Divider.test.js.snap, src/lib/Divider/style/base.js, src/lib/Divider/style/index.js, src/lib/Divider/style/shape.js, src/lib/Image/Image.stories.js, src/lib/Input/__snapshots__/Input.test.js.snap, src/lib/Select/__snapshots__/Select.test.js.snap, src/lib/Textarea/__snapshots__/Textarea.test.js.snap, src/lib/index.js, src/shared/global.js, src/theme/theme.base.js
Création du composant Divider (séparateur), avec et sans texte, avec et sans vague.
=> PGX-2537: component divider

src/lib/Input/Input.js, src/lib/Select/Select.js, src/lib/Textarea/Textarea.js
- remove onChange to allow props.onChange
- make onChange compatible on Textara with props
=> fix : Input, Select & TextAra

src/lib/Grid/Grid.js, src/lib/Grid/Grid.stories.js, src/lib/Grid/Grid.test.js, src/lib/Grid/__snapshots__/Grid.test.js.snap, src/lib/Grid/style/base.js, src/lib/Grid/style/constants.js, src/lib/Grid/style/index.js, src/lib/Title/__snapshots__/Title.test.js.snap, src/lib/Title/style/index.js, src/lib/index.js, src/shared/constants.js, src/theme/theme.base.js
- Création du composant grille
=> PGX-2303: grid component

src/lib/Grid/Grid.js, src/lib/Grid/Grid.stories.js, src/lib/Grid/style/base.js, src/lib/Grid/style/index.js, src/lib/InternalGrid/InternalGrid.js, src/lib/InternalGrid/InternalGrid.stories.js, src/lib/InternalGrid/style/base.js, src/lib/InternalGrid/style/index.js, src/lib/index.js
- Création d'un composant InternalGrid
- Update du composant Grid pour ajouter des options pour les marges et les padding
=> PGX-2911: internal grid

src/lib/ListItem/style/base.js, src/lib/ListItem/style/constants.js, src/lib/ListItem/style/index.js
- Fix sur l'alignement des bullet dans les ListItem contenant plus d'une ligne de texte (ne pas centrer les éléments)
=> fix: bullet alignment with a lot of text in ListItem

src/lib/BannerImage/style/base.js, src/lib/BannerImage/style/maskWaveLeftTop.svg, src/lib/BannerImage/style/maskWaveRightTop.svg, src/lib/Footer/Footer.js, src/lib/Footer/Footer.stories.js, src/lib/Footer/Footer.test.js, src/lib/Footer/style/index.js, src/lib/Footer/style/waveTop.js, src/lib/Image/style/waveLeftBottom.svg, src/lib/Image/style/waveRightBottom.svg, src/lib/List/__snapshots__/List.test.js.snap, src/lib/ListItem/__snapshots__/ListItem.test.js.snap, src/lib/ListItem/style/base.js, src/lib/index.js
=> PGX-2909: component footer

src/lib/Footer/Footer.stories.js, src/lib/Footer/style/index.js, src/lib/FooterList/FooterList.js, src/lib/FooterList/FooterList.stories.js, src/lib/FooterList/FooterList.test.js, src/lib/FooterList/__snapshots__/FooterList.test.js.snap, src/lib/FooterList/style/index.js, src/lib/index.js, src/shared/constants.js
- Création d'un composant FooterList pour gérer les styles des listes dans le footer
- Utilisation de ce composant dans la story du Footer
=> PGX-3398: component FooterList

src/lib/ListItem/style/base.js, src/lib/ListItem/style/index.js, src/lib/Menu/style/index.js, src/lib/MenuList/style/index.js, src/lib/MenuPrimary/style/base.js, src/lib/MenuPrimary/style/index.js
Modification de l'animation du menu pour éviter les bugs au hover.
=> PGX-4056 : fix hover menu

src/lib/AutonomousInput/__snapshots__/AutonomousInput.test.js.snap, src/lib/Header/__snapshots__/Header.test.js.snap, src/lib/Input/__snapshots__/Input.test.js.snap, src/lib/List/__snapshots__/List.test.js.snap, src/lib/ListItem/__snapshots__/ListItem.test.js.snap, src/lib/Loader/Loader.js, src/lib/Loader/Loader.stories.js, src/lib/Loader/Loader.test.js, src/lib/Loader/__snapshots__/Loader.test.js.snap, src/lib/Loader/style/base.js, src/lib/Loader/style/index.js, src/lib/Menu/__snapshots__/Menu.test.js.snap, src/lib/MenuList/__snapshots__/MenuList.test.js.snap, src/lib/MenuPrimary/__snapshots__/MenuPrimary.test.js.snap, src/lib/MenuSecondary/__snapshots__/MenuSecondary.test.js.snap, src/lib/RadioIcon/__snapshots__/RadioIcon.test.js.snap, src/lib/Select/__snapshots__/Select.test.js.snap, src/lib/Textarea/__snapshots__/Textarea.test.js.snap, src/lib/index.js, src/theme/theme.base.js
Création d'un composant Loader, utilisable dans toutes les couleurs du thème, différentes tailles, marges paramétrables, avec une pros `isActive` permettant de le laisser dans une page en "invisible" (améliore l'effet de transition et évite les sautes brutales lorsqu'on l'affiche ou qu'on le masque).
=> PGX-4229; create Loader component

src/lib/Icon/Icon.stories.js, src/lib/Icon/IconWrapper.js, src/lib/Icon/style/index.js, src/lib/List/style/base.js, src/lib/ListItem/style/constants.js, src/shared/constants.js, src/theme/theme.base.js
- Launch the storybook with `yarn storybook`
- Go to section Icon
- Check that IconSize include xxs option and that there is a select for RotationSize
=> PGX-4422 - Amélioration des Icon

src/lib/Badge/Badge.js, src/lib/Badge/Badge.stories.js, src/lib/Badge/Badge.test.js, src/lib/Badge/__snapshots__/Badge.test.js.snap, src/lib/Badge/style/base.js, src/lib/Badge/style/index.js, src/lib/Logo/Logo.js, src/lib/Logo/Logo.stories.js, src/lib/Logo/style/base.js, src/lib/Logo/style/index.js, src/lib/Text/style/constants.js, src/lib/Title/style/constants.js, src/shared/constants.js, src/theme/theme.base.js
- Launch the storybook with yarn storybook
- Go to section Badge
- Check that the Badge respond correctly to the differents options
=> PGX-4421 - Nouveau composant Badge

src/lib/Popin/Popin.js, src/lib/Popin/Popin.stories.js, src/lib/Popin/Popin.test.js, src/lib/Popin/__snapshots__/Popin.test.js.snap, src/lib/Popin/style/base.js, src/lib/Popin/style/index.js, src/lib/index.js
- Launch the storybook with `yarn storybook`
- Got to section Basics/Popin
- Check that the component works correctly
=> PGX-4423 - Nouveau composant Popin

src/lib/Box/Box.js, src/lib/Box/Box.stories.js, src/lib/Box/Box.test.js, src/lib/Box/__snapshots__/Box.test.js.snap, src/lib/Box/style/index.js, src/lib/index.js
- Go to the section Box and test the component
=> PGX-4379 - Nouveau composant Box

src/lib/index.js
- Check that import and export of the component Badge is correctly set in *src/lib/index.js*
=> PGX-4622 - Correction des I/E du composant Badge

src/lib/FooterList/style/index.js, src/lib/ListItem/ListItem.js, src/lib/ListItem/ListItem.stories.js, src/lib/ListItem/style/index.js
- Go to section FooterList
- Resize viewport to mobile to see margin top and bottom appear
- Reset viewport
- Go to section ListItem
- Set property 'Has link' to true, see that there is no margin top and bottom
- Resize viewport to mobile to see margin top and bottom appear
- Set 'Has link' to false, see that there is no more margin top and bottom
=> PGX-4636 - Modification des ListItems

src/lib/ClickableBlock/ClickableBlock.js, src/lib/ClickableBlock/ClickableBlock.stories.js, src/lib/ClickableBlock/ClickableBlock.test.js, src/lib/ClickableBlock/__snapshots__/ClickableBlock.test.js.snap, src/lib/ClickableBlock/style/index.js, src/lib/index.js
- Go to Basics/ClickableBlock and test the component
*You can click on it to change the Icon rotation.*
=> PGX-4425 - Nouveau composant ClickableBlock

src/lib/HR/HR.js, src/lib/HR/HR.stories.js, src/lib/HR/HR.test.js, src/lib/HR/__snapshots__/HR.test.js.snap, src/lib/HR/style/constants.js, src/lib/HR/style/index.js, src/lib/index.js
- Go to section HR
- Check that the HR margin works correctly, same for opacity and colors
=> PGX-4433 - Nouveau composant HR

src/lib/DaLabel/DaLabel.js, src/lib/DaLabel/DaLabel.stories.js, src/lib/DaLabel/DaLabel.test.js, src/lib/DaLabel/__snapshots__/DaLabel.test.js.snap, src/lib/DaLabel/style/index.js, src/lib/index.js, src/shared/constants.js
- Launch the storybook with yarn storybook
- Go to the section form elements / DaLabel
1-DaInput (https://github.com/PayGreen/paygreen-ui/pull/47)
2-DaSelect https://github.com/PayGreen/paygreen-ui/pull/48)
3-DaLabel (vous êtes ici)
4-DaTextarea (https://github.com/PayGreen/paygreen-ui/pull/50)
=> PGX-4604: creation of new component DaLabel

src/shared/constants.js, src/theme/theme.base.js
- Launch the storybook with yarn storybook
- Go to the section form elements / Buttons / DaButton  (or other component with theme color )
- Try quinary color in theme
=> PGF-109: New color quinary in theme

src/lib/AutonomousInput/__snapshots__/AutonomousInput.test.js.snap, src/lib/Checkbox/__snapshots__/Checkbox.test.js.snap, src/lib/CheckboxGroup/__snapshots__/CheckboxGroup.test.js.snap, src/lib/ClickableBlock/ClickableBlock.stories.js, src/lib/DaInput/__snapshots__/DaInput.test.js.snap, src/lib/DaSelect/__snapshots__/DaSelect.test.js.snap, src/lib/DaTextarea/__snapshots__/DaTextarea.test.js.snap, src/lib/Dropdown/Dropdown.js, src/lib/Dropdown/Dropdown.stories.js, src/lib/Dropdown/Dropdown.test.js, src/lib/Dropdown/__snapshots__/Dropdown.test.js.snap, src/lib/Dropdown/style/index.js, src/lib/Input/__snapshots__/Input.test.js.snap, src/lib/MenuPrimary/style/index.js, src/lib/Popin/Popin.js, src/lib/Popin/Popin.stories.js, src/lib/Popin/__snapshots__/Popin.test.js.snap, src/lib/Popin/style/base.js, src/lib/Popin/style/index.js, src/lib/RadioIcon/__snapshots__/RadioIcon.test.js.snap, src/lib/Select/__snapshots__/Select.test.js.snap, src/lib/Textarea/__snapshots__/Textarea.test.js.snap, src/lib/index.js
- Go to section Main/Dropdown
**The Dropdown component has no properties, it's used to spread the onClick of Buttons to activate the Popin. You can test it by clicking on the ClickableBlock, the Badge or the Icon.**
=> PGF-63 - Nouveau composant Dropdown

src/lib/Card/__snapshots__/Card.test.js.snap, src/lib/List/__snapshots__/List.test.js.snap, src/lib/ListHorizontal/__snapshots__/ListHorizontal.test.js.snap, src/lib/ListItem/__snapshots__/ListItem.test.js.snap, src/lib/Menu/__snapshots__/Menu.test.js.snap, src/lib/MenuItem/__snapshots__/MenuItem.test.js.snap, src/lib/MenuList/__snapshots__/MenuList.test.js.snap, src/lib/MenuPrimary/__snapshots__/MenuPrimary.test.js.snap, src/lib/Message/__snapshots__/Message.test.js.snap, src/lib/Modal/__snapshots__/Modal.test.js.snap, src/lib/ModalBody/__snapshots__/ModalBody.test.js.snap, src/lib/ModalContent/__snapshots__/ModalContent.test.js.snap, src/lib/Text/Text.stories.js, src/lib/Text/Text.test.js, src/lib/Text/__snapshots__/Text.test.js.snap, src/lib/Text/style/base.js, src/lib/Text/style/constants.js, src/lib/Text/style/index.js, src/shared/constants.js
- Launch the storybook with yarn storybook
- Go to the section basics/ text / new styled html tags
=> PGF-62: Added new html tags to component text

src/lib/MenuHamburger/MenuHamburger.js, src/lib/MenuHamburger/MenuHamburger.stories.js, src/lib/MenuHamburger/MenuHamburger.test.js, src/lib/MenuHamburger/style/base.js, src/lib/MenuHamburger/style/constants.js, src/lib/MenuHamburger/style/index.js
- yarn storybook
- go to navigation/menuControls/hamburgerMenu : switch from colorTheme to colorWab
=> PGF-156 : Amélioration du burger menu

src/lib/DaTable/DaTable.stories.js, src/lib/DaTable/__snapshots__/DaTable.test.js.snap, src/lib/DaTable/style/index.js, src/lib/DaTableBody/DaTableBody.js, src/lib/DaTableBody/DaTableBody.stories.js, src/lib/DaTableBody/DaTableBody.test.js, src/lib/DaTableBody/__snapshots__/DaTableBody.test.js.snap, src/lib/DaTableBody/style/index.js, src/lib/DaTableHead/__snapshots__/DaTableHead.test.js.snap, src/lib/DaTableHead/style/index.js, src/lib/index.js
- Ajout du composant DaTableBody
- Utilisation de ce composant dans le DaTable
- Ajustements de style pour optimiser les couleurs de fond grâce au DaTableBody
=> PGF-190 : create DaTableBody component

src/lib/AutonomousInput/__snapshots__/AutonomousInput.test.js.snap, src/lib/Checkbox/__snapshots__/Checkbox.test.js.snap, src/lib/CheckboxGroup/__snapshots__/CheckboxGroup.test.js.snap, src/lib/Corner/__snapshots__/Corner.test.js.snap, src/lib/DaInput/__snapshots__/DaInput.test.js.snap, src/lib/DaSelect/__snapshots__/DaSelect.test.js.snap, src/lib/DaTextarea/__snapshots__/DaTextarea.test.js.snap, src/lib/DataBar/__snapshots__/DataBar.test.js.snap, src/lib/FormControl/__snapshots__/FormControl.test.js.snap, src/lib/Input/__snapshots__/Input.test.js.snap, src/lib/ModalContent/__snapshots__/ModalContent.test.js.snap, src/lib/ModalHeader/__snapshots__/ModalHeader.test.js.snap, src/lib/ModalHeader/style/index.js, src/lib/Radio/__snapshots__/Radio.test.js.snap, src/lib/RadioGroup/__snapshots__/RadioGroup.test.js.snap, src/lib/RadioIcon/__snapshots__/RadioIcon.test.js.snap, src/lib/Select/__snapshots__/Select.test.js.snap, src/lib/Textarea/__snapshots__/Textarea.test.js.snap, src/lib/Toggle/Toggle.js, src/lib/Toggle/Toggle.stories.js, src/lib/Toggle/Toggle.test.js, src/lib/Toggle/__snapshots__/Toggle.test.js.snap, src/lib/Toggle/style/constants.js, src/lib/Toggle/style/index.js, src/lib/index.js, src/theme/theme.base.js
Création d'un composant Toggle : 
- Couleurs paramétrables (dans la mesure du raisonnable)
- Label général optionnel
- Possibilité de laisser le Toggle vide, y mettre des textes ou des Icons, et même de faire un mix (un icon d'un côté, rien de l'autre, un texte d'un côté, un icon de l'autre, etc)
- Le Toggle est un input checkbox classique sur lequel on peut passer n'importe quel attribut additionnel (via le ...rest).
Guide des couleurs : 
- ColorPallet = theme : le toggle inactif est en gris et passe en colorTheme lorsqu'il devient actif (ça n'aurait pas de sens de mélanger une couleur de thème avec une autre couleur pour indiquer la version active/passive, genre violet et orange, ça correspond à rien, d'où le choix du gris).
- ColorPallet = wab: le toggle inactif est en gris et passe en …
=> PGF-9: Toggle component

src/lib/Header/Header.stories.js, src/lib/MenuGroup/MenuGroup.stories.js, src/lib/MenuGroup/style/base.js, src/lib/MenuGroup/style/index.js, src/lib/MenuPrimary/MenuPrimary.stories.js, src/shared/global.js
- Fix de la couleur des liens dans le Header transparent
=> PGF-211: fix header links color

src/lib/DatePicker/DatePickerInput/DatePickerInput.js, src/lib/DatePicker/DatePickerInput/DatePickerInput.stories.js, src/lib/DatePicker/DatePickerInput/DatePickerInput.test.js, src/lib/DatePicker/DatePickerInput/__snapshots__/DatePickerInput.test.js.snap, src/lib/DatePicker/DatePickerInput/style/base.js, src/lib/DatePicker/DatePickerInput/style/index.js
**This PR's content will not be used! Review and recette are not necessary!**
This PR includes a new component DatePickerInput that will be used in the DatePicker component.
Go to storybook and try to break the component. If everything works as expected, it's good.
_NB: Waiting PGF-238 for style!_
_NB bis: Don't forget to read the documentation in Notion -> https://www.notion.so/paygreen/Analyse-R-alisation-Datepicker-276aa1f6af1c44ba864768554a8d48d7_
=> PGF-234 - Component DatePickerInput

src/lib/DatePicker/DatePicker/DatePicker.js, src/lib/DatePicker/DatePicker/DatePicker.stories.js, src/lib/DatePicker/DatePicker/DatePicker.test.js, src/lib/DatePicker/DatePicker/__snapshots__/DatePicker.test.js.snap, src/lib/DatePicker/DatePicker/style/index.js, src/lib/Popin/Popin.js, src/lib/Popin/style/index.js, src/lib/index.js
This PR includes the new component DatePicker.
Go to storybook and try to break the component. If everything works as expected, it's good.
**During review/recette, do not pay attention to style. There is a PR for this!**
_NB: Waiting PGF-238 for style!_
_NB bis: Don't forget to read the documentation in Notion -> https://www.notion.so/paygreen/Analyse-R-alisation-Datepicker-276aa1f6af1c44ba864768554a8d48d7_
=> PGF-233 - Component DatePicker

README.md
This PR add a README.md file to the project to give some informations concerning the library.
=> PGF-268 - Base de documentation pour PG-UI

src/lib/GlobalStyle/AutoBlockScroll.js, src/lib/GlobalStyle/GlobalStyle.js, src/lib/ModalGroup/ModalGroup.js, src/lib/ModalGroup/ModalGroup.stories.js, src/lib/ModalGroup/__snapshots__/ModalGroup.test.js.snap, src/lib/ModalGroup/style/index.js, src/lib/index.js, src/shared/hook/useWindowSize.js
- `yarn storybook`
-  go to ModalGroup : 
- check if scroll is blocked when modal is opened, no scroll bar added
- add text to create scroll/overflow in window , check if scroll is blocked when modal is opened and that scroll bar has not been removed at the same time :)
=> PGF-366: added global noscroll style components for modal and menus

src/lib/DatePicker/Calendar/__snapshots__/Calendar.test.js.snap, src/lib/DatePicker/CalendarCell/__snapshots__/CalendarCell.test.js.snap, src/lib/DatePicker/CalendarGrid/__snapshots__/CalendarGrid.test.js.snap, src/lib/Header/__snapshots__/Header.test.js.snap, src/lib/MenuGroup/MenuGroup.js, src/lib/MenuGroup/__snapshots__/MenuGroup.test.js.snap, src/lib/MenuGroup/style/base.js, src/lib/MenuSecondary/__snapshots__/MenuSecondary.test.js.snap, src/lib/MenuSecondary/style/index.js
- Fix de couleurs sur Dot dans le MenuGroup en reverse
- Fix de la largeur des MenuList dans les MenuSecondary
=> PGF-504: fix on Menu components

src/lib/Grid/Grid.stories.js, src/lib/Grid/style/base.js, src/lib/Loader/Loader.stories.js, src/lib/Skeleton/Skeleton.js, src/lib/Skeleton/Skeleton.stories.js, src/lib/Skeleton/Skeleton.test.js, src/lib/Skeleton/__snapshots__/Skeleton.test.js.snap, src/lib/Skeleton/style/SkeletonTypes.js, src/lib/Skeleton/style/base.js, src/lib/Skeleton/style/index.js, src/lib/SkeletonItem/SkeletonItem.js, src/lib/SkeletonItem/SkeletonItem.stories.js, src/lib/SkeletonItem/SkeletonItem.test.js, src/lib/SkeletonItem/__snapshots__/SkeletonItem.test.js.snap, src/lib/SkeletonItem/style/base.js, src/lib/SkeletonItem/style/index.js, src/lib/index.js, src/shared/constants.js, src/shared/spaces.js, src/theme/theme.base.js, yarn.lock
voir ticket PGF-323
- modifs supplémentaires : sur le composant Grid, forcer les margins des enfants ayant leur margins propres en rajoutant "!important"
- `yarn storybook`
- aller à SkeletonItem et Skeleton
=> PGF-323: creation of skeletonItem and skeleton components

.storybook/preview-head.html, src/lib/Dropdown/Dropdown.js, src/lib/Dropdown/__snapshots__/Dropdown.test.js.snap, src/lib/FormControl/FormControl.stories.js, src/lib/HistogramBar/HistogramBar.js, src/lib/Message/Message.js, src/lib/Message/Message.stories.js, src/lib/Popin/Popin.js, src/lib/Popin/Popin.stories.js, src/lib/Popin/__snapshots__/Popin.test.js.snap, src/lib/Popin/style/base.js, src/lib/Popin/style/index.js, src/shared/constants.js, src/shared/global.js
- Utilisation du rest et non des props sur le composant Dropdown
- Passage à un switch plus lisible
- Déplacement de l'instruction font-family dans le global.js (pour ne pas l'oublier quand on copie le style dans d'autres projets, sinon on n'a pas la bonne police)(rien à voir avec le Dropdown, c'était juste en passant)
- Ajout d'options de positions pour la Popin (ce qui modifie légèrement la constante également utilisée pour les Message, d'où les modifications sur ses fichiers).
**Toutes les modifications apportées dans cette PR sont rétro-compatibles (aucun changement à faire à l'intégration).**
=> PGF-531: fix Dropdown props

src/lib/GlobalStyle/AutoBlockScroll.js, src/lib/GlobalStyle/GlobalStyle.js, src/lib/Histogram/__snapshots__/Histogram.test.js.snap, src/lib/Histogram/style/index.js, src/lib/HistogramBar/HistogramBar.js, src/lib/MenuGroup/style/base.js, src/lib/MenuPrimary/MenuPrimary.js, src/lib/MenuSecondary/MenuSecondary.js, src/lib/MenuTertiary/MenuTertiary.js, src/lib/ModalGroup/ModalGroup.js, src/shared/hook/index.js
- Fix: MenuList masqués dans un MenuGroup fermé
- Feat: pouvoir choisir de bloquer le scroll seulement sur mobile via AutoBlockScroll
- Feat: scrollbar masquée quand le MenuPrimary est ouvert sur mobile
- Fix: erreur de return vide dans les HistogramBar appelés par le composant Histogram
- Feat: style pour un Histogram sans datas
=> PGF-545: fix MenuList and Histogram

src/lib/Card/Card.stories.js, src/lib/Corner/Corner.js, src/lib/Corner/Corner.stories.js, src/lib/Corner/style/base.js, src/lib/Corner/style/index.js, src/lib/Layout/Layout.stories.js, src/lib/MenuClose/MenuClose.js, src/lib/MenuClose/MenuClose.stories.js, src/lib/MenuClose/__snapshots__/MenuClose.test.js.snap, src/lib/MenuClose/style/base.js, src/lib/MenuClose/style/index.js, src/lib/MenuGroup/__snapshots__/MenuGroup.test.js.snap, src/lib/MenuHamburger/MenuHamburger.js, src/lib/MenuHamburger/MenuHamburger.stories.js, src/shared/constants.js
- Feat : ajout d'une props pour choisir la position du MenuClose (top, bottom, left, right)
- Feat : ajout d'un hover sur le MenuClose
- Refacto de certaines constantes de direction/position
> Attention : sur le composant Corner, la props `cornerPosition` s'appelle désormais `position` tout court !
=> PGF-567: improve MenuClose component

src/lib/DataLegend/__snapshots__/DataLegend.test.js.snap, src/lib/DataLegend/style/index.js, src/lib/Overlay/Overlay.js, src/lib/Overlay/Overlay.stories.js, src/lib/Overlay/style/base.js, src/shared/constants.js
- Fix sur le DataLegend (le Text doit être en inline)
- Ajout d'une props sur l'Overlay pour choisir la teinte du gris/noir/blanc lorsque le gradient est à none
=> PGF-578 : Overlay choose ColorWab

src/lib/DataLegend/__snapshots__/DataLegend.test.js.snap, src/lib/DataLegend/style/index.js, src/lib/Table/__snapshots__/Table.test.js.snap, src/lib/Table/style/base.js, src/lib/Table/style/index.js, src/lib/TableCell/__snapshots__/TableCell.test.js.snap, src/lib/TableCell/style/index.js, src/lib/TableRow/__snapshots__/TableRow.test.js.snap, src/lib/TableRow/style/base.js, src/lib/TableRow/style/index.js, src/lib/Text/style/base.js
- Amélioration du responsive du composant Table
- Fix du DataLegend et du Text (j'avais passé le Text dans les DataLegend en display inline en croyant qu'il y avait eu un truc qui avait sauté, mais en fait le souci venait du Text en span à qui on avait retiré le précieux display inline-block, donc c'est corrigé !)
=> PGF-563: improve table responsive

src/lib/Card/Card.js, src/lib/DaHelp/DaHelp.js, src/lib/DatePicker/CalendarCell/CalendarCell.js, src/lib/DatePicker/DatePicker.js, src/lib/DatePicker/DatePicker.stories.js, src/lib/FormControl/FormControl.js, src/lib/FormControl/FormControl.stories.js, src/lib/Icon/IconWrapper.js, src/lib/Logo/Logo.js, src/lib/Logo/Logo.stories.js, src/lib/Logo/style/index.js, src/lib/MenuClose/MenuClose.js, src/lib/PaginationItem/PaginationItem.js, src/lib/SidebarItem/SidebarItem.js
FormControl
-------
Retrait de la props `hasHelpButton` sur le composant FormControl : désormais, il vérifie tout seul s'il a un enfant DaHelp et remplit cette props tout seul pour appliquer les bons styles (sur lui-même ET sur les enfants qui ont cette props `hasHelpButton`.
Cela ne change absolument rien sur le style desdits composants par rapport aux versions antérieures : cette modification permet de simplifier leur intégration, puisque l'intégrateur n'a plus à ajouter manuellement cette props afin d'appliquer le style voulu.
Les anciennes intégrations fonctionnent toujours : "forcer" la props `hasHelpButton` sur un FormControl ou sur un DaInput contenu dans un FormControl n'a absolument aucun effet (seule la présence effective d'un DaHelp va déclencher ou non l'application des styles …
=> PGF-663: remove hasHelpButton props in FormControl, add type button on components, add align option on Logo and fix reset date in DatePicker

src/lib/Card/Card.stories.js, src/lib/Card/style/base.js
- Fix du style pour le borderTop de la Card : à présent, même avec du padding, ça va bien se passer
- Ajout de padding dans la storie de la Card pour visualiser que tout se passe bien
=> PGF-37: fix: borderTop position inside Card

src/lib/Grid/Grid.js, src/lib/Grid/Grid.stories.js, src/lib/Grid/style/base.js, src/lib/InternalGrid/style/base.js, website/docs/Grids/Grid/ChildrenMargin.mdx, website/docs/Grids/Grid/ChildrenShift.mdx, website/docs/Grids/Grid/DisplayTypeColumn.mdx, website/docs/Grids/Grid/DisplayTypeFlex.mdx, website/docs/Grids/Grid/DisplayTypeGrid.mdx, website/docs/Grids/Grid/Use.mdx, website/docs/Grids/GridGap.mdx, website/docs/Grids/InternalGrid/DisplayTypeFlex.mdx, website/docs/Grids/InternalGrid/DisplayTypeGrid.mdx, website/docs/Grids/InternalGrid/Use.mdx, website/docs/theme.mdx
- Doc pour le composant Grid
- Refacto du style de la Grid pour que ce soit moins le bazar
=> PGF-821: doc Grid

README.md, src/lib/Icon/Icon.stories.js, src/shared/labels.js, src/theme/colors.js, src/theme/theme.dark.js, src/theme/theme.default.js
- Ajout d'une doc (en français déso) pour les développeurs
- Ajout d'un label manquant
- Réorganisation des icons dans la storie pour que ce soit plus visuel
- Refacto des couleurs du thème pour qu'elles soient toutes dans un seul et même fichier (plus clair)
=> PGF-912: add doc for developers

src/lib/BannerImage/BannerImage.js, src/lib/BannerImage/BannerImage.stories.js, src/lib/BannerImage/__snapshots__/BannerImage.test.js.snap, src/lib/BannerImage/style/base.js, src/lib/BannerImage/style/index.js, src/lib/BannerImage/style/maskWaveLeftBottom.svg, src/lib/BannerImage/style/maskWaveRightBottom.svg, src/lib/Footer/__snapshots__/Footer.test.js.snap, src/lib/Footer/style/index.js, src/lib/Image/Image.stories.js, src/shared/constants.js, src/shared/labels.js, src/theme/theme.base.js
-----
- Ajout d'une prop pour choisir soit la couleur de l'image soit une couleur du thème (`hasModifiedColor`)
- Ajout d'une prop pour choisir le masque en bas de l'image (`bottomStyle`), par défaut en `gradient`
- Refacto code BannerImage et style du Footer
Ce qu'il faut tester
-------
- **BannerImage**
- **Footer**
=> PGF-898: improve BannerImage component

src/lib/Box/__snapshots__/Box.test.js.snap, src/lib/Box/style/index.js, src/lib/Layout/__snapshots__/Layout.test.js.snap, src/lib/Main/__snapshots__/Main.test.js.snap, src/lib/Toggle/Toggle.js, src/lib/Toggle/Toggle.stories.js, src/lib/Toggle/__snapshots__/Toggle.test.js.snap, src/lib/Toggle/style/base.js, src/lib/Toggle/style/index.js
-----
- Prise en compte du `disabled` dans le style du **Toggle**
- Petit refacto au passage : utilisation des helpers de Fanny dans le style du composant Box (on avait un vieux ticket pour faire ça qui traînait depuis un moment, donc comme ça c'est réglé)
Comment tester
------
- Aller sur la storie du **Toggle** et tester la props `disabled`
- Aller sur la storie de la **Box** et tester les props
=> PGF-975: feat: add disabled prop style on Toggle
